[package]
name = "parkind_client"
version = "0.1.0"
authors = ["kornel"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.46"
clap = "3.0.0-beta.2"
